version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "America/Denver"
    #assignees:
    #  - "username"
    #labels: need to add the required label to the repo first!
    #  - "submodule-updates"
    # must use the full team name, including the organization, as if you were @mentioning the team
    reviewers:
      - "tangxifan"
      - "tpagarani"
    # Allow dependabot to open up to 10 open pull requests. Default is 5.
    # open-pull-requests-limit: 10
    allow:
      # only enable for the yosys-symbiflow-plugins submodule
      - dependency-name: "yosys-plugins"
